apiVersion: v1
kind: ServiceAccount
metadata:
  name: openapi-operator
  namespace: default
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: services-manage
rules:
- apiGroups: [""]
  resources: ["services", "endpoints"]
  verbs: ["get","list","watch"]

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: services-manage
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: services-manage
subjects:
- kind: ServiceAccount
  namespace: default
  name: openapi-operator
---
apiVersion: v1
kind: Service
metadata:
  name: openapi-operator
spec:
  selector:
    app: openapi-operator
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: openapi-operator
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: openapi-operator
    spec:
      serviceAccountName: openapi-operator
      terminationGracePeriodSeconds: 10
      containers:
        - name: openapi-operator
          image: plugandtrade/openapi-operator
          imagePullPolicy: Always
          env:
            - name: K8S_MODE
              value: "in_cluster"
          ports:
            - name: http
              containerPort: 4000
